runMode: debug                                  # 开发模式, debug, release, test
addr: :80                                     # HTTP绑定端口

log:
  writers: file,stdout            # 输出位置.file将日志记录到 logger_file 指定的日志文件中;stdout 会将日志输出到标准输出; 也可以两者同时选择
  logger_level: DEBUG             # 日志级别 DEBUG、INFO、WARN、ERROR、FATAL
  logger_file: log/apiServer.log  # 日志文件
  log_format_text: false          # 日志的输出格式 JSON(false) 或者 plaintext(true)
  rollingPolicy: size             # rotate 依据 选 daily 则根据天进行转存，如果是 size 则根据大小进行转存
  log_rotate_date: 1              # rotate 转存时间，配 合rollingPolicy: daily 使用
  log_rotate_size: 1              # rotate 转存大小，配合 rollingPolicy: size 使用
  log_backup_count: 7             # 当日志文件达到转存标准时，log 系统会将该日志文件进行压缩备份，这里指定了备份文件的最大个数

db:
  name: indoor_positioning
  addr: 39.101.75.158:2001
  encoded: utf8mb4
  username: root
  password: GHY20010701ghy

  jwt_secret: 8]2f+C?x|x_UFpe$tqpGm>L6Rw*!uRqD

time:
  layout: "2023-04-10T16:00:00.000Z"